In [3]:
import numpy as np
import pandas as pd

## Exercício 66
Crie um array unidimensional com os primeiros 10 números primos e, em seguida, imprima apenas os números ímpares desse array.

In [ ]:
primos = np.array([2, 5, 7, 11, 13, 17, 19, 23, 29, 31])
primos[numeros_primos % 2 != 0]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

Podemos fazer também utilizando as funções do pandas:

In [ ]:
# Criarndo um array unidimensional (pd.series)
numeros_primos = pd.Series(data = [2, 5, 7, 11, 13, 17, 19, 23, 29, 31])
numeros_primos

0     2
1     5
2     7
3    11
4    13
5    17
6    19
7    23
8    29
9    31
dtype: int64

In [ ]:
numeros_primos[numeros_primos % 2 != 0]

1     5
2     7
3    11
4    13
5    17
6    19
7    23
8    29
9    31
dtype: int64

In [ ]:
# podemos armazenar os filtros dentro de uma variável
numeros_pares = numeros_primos % 2 == 0
numeros_impares = numeros_primos % 2 != 0

In [ ]:
numeros_primos[numeros_pares]

0    2
dtype: int64

In [ ]:
numeros_primos[numeros_impares]

1     5
2     7
3    11
4    13
5    17
6    19
7    23
8    29
9    31
dtype: int64

In [ ]:
primos[numeros_impares]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

## Exercício 67

Crie uma matriz 3x3 com valores aleatórios entre 1 e 10. Em seguida, calcule a média dos valores em cada linha e imprima o resultado.

In [ ]:
matriz = np.random.rand(3, 3) * 10

matriz

array([[4.08118673, 3.62184539, 8.46464912],
       [2.79351565, 2.86629785, 8.9348401 ],
       [6.60087811, 0.92896093, 6.75023397]])

In [ ]:
# fixar os números aleatórios
np.random.seed(0)
array = np.random.randint(1, 10, size = (3, 3))
array

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [ ]:
# calculando a média de cada linha
array.mean(axis = 1)

array([3.66666667, 5.33333333, 4.66666667])

In [ ]:
array.mean(axis = 0) # média das colunas

array([5.33333333, 4.        , 4.33333333])

Utilizando as funções do pandas:

In [ ]:
matriz = pd.DataFrame(data = {'linha 1': [1, 2, 3],
                              'linha 2': [10, 7, 7],
                              'linha 3': [5, 6, 9]})

In [ ]:
matriz.describe()

linha 1    linha 2   linha 3
count      3.0   3.000000  3.000000
mean       2.0   8.000000  6.666667
std        1.0   1.732051  2.081666
min        1.0   7.000000  5.000000
25%        1.5   7.000000  5.500000
50%        2.0   7.000000  6.000000
75%        2.5   8.500000  7.500000
max        3.0  10.000000  9.000000

In [ ]:
print(f"Média da coluna 'linha 1': {matriz['linha 1'].mean()}")
print(f"Média da coluna 'linha 2': {matriz['linha 2'].mean()}")
print(f"Média da coluna 'linha 3': {matriz['linha 3'].mean()}")

Média da coluna 'linha 1': 2.0
Média da coluna 'linha 2': 8.0
Média da coluna 'linha 3': 6.666666666666667


## Exercício 68
Crie um array unidimensional com números inteiros de 1 a 20. Em seguida, substitua todos os números pares por zero e imprima o array resultante.

In [ ]:
np.random.seed(0)
array_inteiro = np.random.randint(1, 20, size = 10)
array_inteiro

array([13, 16,  1,  4,  4,  8, 10, 19,  5,  7])

In [ ]:
np.where(array_inteiro % 2 == 0, 0, array_inteiro)

array([13,  0,  1,  0,  0,  0,  0, 19,  5,  7])

## Exercício 69

Crie duas matrizes 2x2 e realize a multiplicação de matriz entre elas. Imprima a matriz resultante.

In [ ]:
np.random.seed(0)

matriz_1 = np.random.randint(1, 10, size = (2, 2))
matriz_1

array([[6, 1],
       [4, 4]])

In [ ]:
np.random.seed(2)

matriz_2 = np.random.randint(1, 10, size = (2, 2))
matriz_2

array([[9, 9],
       [7, 3]])

In [ ]:
multiplicacao_matriz = matriz_1 * matriz_2
multiplicacao_matriz

array([[54,  9],
       [28, 12]])

<img src='https://escolaeducacao.com.br/wp-content/uploads/2020/04/multiplicacao-de-matrizes.jpg'>

In [ ]:
# multiplicação de matriz igual na foto acima - utilizamos a função matmul
np.matmul(matriz_1, matriz_2)

array([[61, 57],
       [64, 48]])

## Exercício 70
Crie um array unidimensional com 100 números inteiros aleatórios. Encontre o valor máximo, o valor mínimo, a média e o desvio padrão desses números e imprima os resultados.

In [11]:
np.random.seed(0)

array_100 = np.random.randint(low=18, high=90, size=100)
array_100

array([62, 65, 82, 85, 85, 27, 39, 54, 88, 30, 76, 83, 57, 64, 55, 43, 27,
       38, 87, 65, 82, 67, 47, 37, 37, 32, 57, 50, 83, 27, 75, 50, 49, 41,
       53, 73, 46, 52, 18, 18, 54, 71, 23, 56, 35, 22, 60, 76, 49, 19, 83,
       59, 75, 53, 29, 64, 18, 32, 71, 30, 60, 86, 24, 86, 65, 21, 70, 33,
       38, 76, 41, 31, 66, 67, 87, 59, 53, 82, 87, 18, 68, 54, 52, 66, 21,
       60, 39, 18, 28, 61, 76, 41, 77, 20, 80, 53, 85, 64, 38, 68])

In [14]:
print(f"Valor mínimo: {array_100.min()}")
print(f"Valor máximo: {array_100.max()}")
print(f"Média: {array_100.mean()}")
print(f"Desvio Padrão: {array_100.std()}")

Valor mínimo: 18
Valor máximo: 88
Média: 54.04
Desvio Padrão: 21.193357449918125


## Exercício 71
Suponha que você tenha um modelo que retorna probabilidades contínuas e você deseja aplicar um threshold para atribuir classes binárias (0 ou 1). Crie um programa que simule esse processo usando a função `np.where()` do NumPy.

A lista de probabilidades é a seguinte: `y_pred_probs = np.array([0.4, 0.6, 0.2. 0.3, 0.8, 0.9, 0.1, 0.8, 0.4, 0.5])`

In [17]:
y_pred_probs = np.array([0.4, 0.6, 0.2, 0.3, 0.8, 0.9, 0.1, 0.8, 0.4, 0.5])
y_pred_probs

array([0.4, 0.6, 0.2, 0.3, 0.8, 0.9, 0.1, 0.8, 0.4, 0.5])

**O que é threshold?**

Threshold, em inglês, significa "limiar" ou "limite". Em diferentes contextos, o termo pode ter significados diferentes, mas geralmente se refere a um ponto crítico ou valor a partir do qual algo acontece ou é tomada uma decisão.

Ou seja, para esse exercicios iremos alterar os elementos dentro do array em relação a um limite, onde números menores que 0.5 serão alterados para zero e números maiores que o.5 serão alterados para 1.


In [18]:
np.where(y_pred_probs >= 0.5, 1, 0)

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])